import type { Metadata } from "next";
import Link from "next/link";
import { requireAdminPage } from "@/lib/admin/auth";
import { adminFailures, adminModules, endpointGuide, pageGuide } from "@/lib/admin/guide";

export const metadata: Metadata = { title: "Admin · Platform guide", robots: { index: false, follow: false } };
export default async function AdminGuidePage() {
  await requireAdminPage("/admin/guide");
  return <div className="admin-page"><p className="eyebrow">Operator handbook</p><h1 className="admin-title">The complete admin guide</h1><p className="admin-intro">Modules, page routes, endpoints, permissions, setup and incident handling. This reference describes implemented behavior, including what is intentionally not automated.</p><nav className="admin-actions mb-8" aria-label="Guide sections">{[["modules", "Modules"], ["setup", "Setup"], ["pages", "Page routes"], ["apis", "API endpoints"], ["safety", "Safety"], ["failures", "Troubleshooting"]].map(([id, name]) => <a className="button-secondary" key={id} href={`#${id}`}>{name}</a>)}</nav><div className="admin-guide">
    <section id="modules" className="admin-panel"><h2>Modules and daily workflows</h2>{adminModules.map(module => <article key={module.path} className="border-t border-border-subtle py-5"><h3>{module.name}</h3><Link href={module.path}><code>{module.path}</code> →</Link><p>{module.purpose}</p><p className="mt-2">{module.workflow}</p></article>)}</section>
    <section id="setup" className="admin-panel"><h2>Setup and administrator access</h2><ol className="list-decimal space-y-3 pl-5"><li>Bootstrap the first administrator in Appwrite Console by adding the exact <code>admin</code> label to a trusted account. Do not use profile settings to assign roles.</li><li>Configure <code>APPWRITE_ADMIN_AUDIT_COLLECTION_ID</code> to a private, ownerless collection ID in the existing database, then run the dedicated opt-in setup below with a schema-management key. It does not change other collection ACLs.</li><li>Runtime admin content/attendance operations require document read/write. Member browsing requires <code>users.read</code>; account status/labels/session controls require the corresponding Users API write scopes supported by your Appwrite version. Keep schema-management scopes out of the runtime key.</li><li>Persist <code>APPWRITE_CHECKIN_SECRET</code> separately from the API key. Use the actual HTTPS <code>NEXT_PUBLIC_SITE_URL</code>, HttpOnly Secure cookies and an ingress rate limiter. Never place keys or signing secrets under <code>NEXT_PUBLIC_</code>.</li></ol><pre><code>{"# Set the private audit collection ID in your ignored environment file first\nnpm run appwrite:admin-audit\n\n# Local verification\nnpm run lint\nnpm run typecheck\nnpm test\nnpm run build"}</code></pre><h3>Audit collection schema</h3><p><code>actorId</code> (36), <code>action</code> (80), <code>target</code> (160), <code>reason</code> (300), <code>status</code> (20), <code>occurredAt</code> datetime, optional <code>finishedAt</code> datetime. Index <code>audit_time</code> on <code>occurredAt</code>. No collection/document client grants; document security enabled. The application refuses to write without durable audit intent.</p><h3>Deployment</h3><pre><code>{"npm run cloudflare:build\nnpm run cloudflare:deploy"}</code></pre><p>Dashboard controls do not provision DNS, rotate secrets, run shell commands, send messages or deploy the Worker. Use the infrastructure console for those jobs. ACL tooling currently assumes empty collection grants while the existing public-table policy may differ: inspect the policy before running the general setup/permission-sync tools.</p></section>
    <section id="pages" className="admin-panel"><h2>Page route reference</h2><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Path</th><th>Access</th><th>Functionality</th></tr></thead><tbody>{pageGuide.map(([path, access, description]) => <tr key={path}><th scope="row"><code>{path}</code></th><td>{access}</td><td>{description}</td></tr>)}</tbody></table></div></section>
    <section id="apis" className="admin-panel"><h2>API endpoint reference</h2><p className="mb-4">All admin APIs independently check the current session and exact admin label. Writes also enforce origin, rate limit, validated JSON and audit intent. API responses are private/no-store. API URLs are documentation, not mutation links.</p><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Methods</th><th>Endpoint</th><th>Access</th><th>Functionality</th></tr></thead><tbody>{endpointGuide.map(([method, path, access, description]) => <tr key={`${method}-${path}`}><th scope="row">{method}</th><td><code>{path}</code></td><td>{access}</td><td>{description}</td></tr>)}</tbody></table></div></section>
    <section id="safety" className="admin-panel"><h2>Safety, privacy and limitations</h2><ul><li>Public content tables may have collection-level public read grants. A draft in those tables is not a secrecy boundary against direct Appwrite API access. Do not put secrets, contact records or moderation notes inside content payloads; private data belongs in owner-only collections.</li><li>Public pages return only published content. Admin pages and APIs authenticate before querying private records. Search indexing is disabled but is not access control.</li><li>Member management exposes minimal operational account selectors so actions can target the correct person. It never returns email addresses, passwords, preferences or session secrets. Do not use the tool to browse private member interests.</li><li>Attendance repair derives verification from an already committed trusted check-in. No button fabricates a session, approves an RSVP as attendance or awards arbitrary fitness credit.</li><li>Deletion checks references but does not provide a distributed transaction. Prefer draft/unpublish to preserve history and avoid racing participation writes. Stale content checks are advisory concurrency protection, not a lock.</li><li>Reasons are operator-supplied text. Do not enter keys, emails, passwords or sensitive personal details. Audit retention/backup and real incident procedures are deployment responsibilities.</li><li>No payments, refunds, provider OAuth, broadcasts, push notifications, club staff invitations, waitlist promotion or analytics tracking have been faked. Those need separate integrations and data models.</li><li>Suspension stops account access through Appwrite. Session revocation is a separate action. Hiding a public profile sets it private; it does not delete the account or history. The member may subsequently use their own privacy controls; suspension is the stronger access measure.</li><li>Admin status/label changes preserve unrelated labels. Self-targeted access controls are blocked so the acting administrator cannot remove their own current access through this UI.</li></ul></section>
    <section id="failures" className="admin-panel"><h2>Troubleshooting and incident playbook</h2>{adminFailures.map(([code, help]) => <div key={code} className="border-t border-border-subtle py-4"><h3><code>{code}</code></h3><p>{help}</p></div>)}<h3>Before public launch</h3><ul><li>Replace fictional listings; confirm times, venue access, hosts and costs.</li><li>Test an admin and a non-admin account on staging: mutations, persistence, role changes, RSVP, QR, repair and logout.</li><li>Verify custom-domain origin/cookies, Appwrite availability, backups, email recovery and access logs.</li><li>Run real-device QR and Safari checks. Synthetic browser tests do not prove physical attendance or hosted persistence.</li></ul></section>
  </div></div>;
}
