import type { Metadata } from "next";
import Link from "next/link";
import { SearchForm } from "@/components/discovery/SearchForm";
import { getDirectory } from "@/lib/data";
import { filterDirectory, readFilters } from "@/components/discovery/filter";

export const metadata: Metadata = { title: "Fitness Activities in Noida", description: "Browse running, cycling, strength, sports, wellness, and outdoor activities with local sessions and communities in Noida.", alternates: { canonical: "/activities" } };
export default async function ActivitiesPage() {
  const directory = await getDirectory();
  const { activities } = directory;
  return <div className="activities-page min-h-full pb-16"><header className="activities-header border-b border-border-subtle bg-background px-4 py-4 sm:px-6 sm:py-5 lg:px-8"><div className="mx-auto max-w-7xl"><h1 className="text-2xl font-bold tracking-tight">Activities</h1><SearchForm id="activities-search" className="mt-3 max-w-2xl" action="/discover" placeholder="Search an activity, sector, or venue" /></div></header><div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 sm:py-16 lg:px-8"><div className="activities-grid grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{activities.map((activity) => { const results = filterDirectory(directory, readFilters({ activity: activity.slug })); const communities = results.communities.length; const events = results.events.length; return <article key={activity.id} className="activity-tile group flex flex-col rounded-2xl border border-border-subtle bg-surface p-6 transition-colors hover:border-border-strong hover:bg-surface-hover"><div className="flex items-center justify-between"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-surface-elevated text-2xl" aria-hidden="true">{activity.emoji}</span><span className="font-mono text-[10px] uppercase tracking-widest text-text-muted">{events} upcoming</span></div><h2 className="mt-6 text-xl font-bold text-white group-hover:text-velocity-glow"><Link className="inline-flex min-h-11 items-center" href={`/activities/${activity.slug}`}>{activity.name}</Link></h2><p className="mt-2 flex-1 text-sm leading-relaxed text-text-secondary">{activity.description}</p><div className="mt-6 flex items-center justify-between border-t border-border-subtle pt-4"><span className="text-xs text-text-muted">{communities} {communities === 1 ? "community" : "communities"}</span><Link href={`/discover?activity=${encodeURIComponent(activity.slug)}`} className="inline-flex min-h-11 items-center text-xs font-bold text-velocity">Explore →</Link></div></article>; })}</div>{activities.length === 0 && <div className="rounded-xl border border-dashed border-border-strong px-6 py-14 text-center text-sm text-text-secondary">Activities will appear here as the directory is published.</div>}<section className="mt-16 rounded-2xl border border-border-subtle bg-surface p-7 sm:p-9"><h2 className="text-2xl font-bold text-white">Not sure where you fit?</h2><p className="mt-2 max-w-xl text-sm leading-relaxed text-text-secondary">Search by sector or venue instead. Noida Stadium, Sector 137, and the Expressway are useful places to begin.</p><Link href="/discover" className="mt-5 inline-flex min-h-11 items-center rounded-lg bg-velocity px-5 text-sm font-bold text-slate-950 hover:bg-velocity-glow">Open discovery</Link></section></div></div>;
}
